#
# Device trackers
#
# @link https://home-assistant.io/components/device_tracker/
#


#
# Bluetooth
#
# Disabled until deemed useful or not.
#
# https://home-assistant.io/components/device_tracker.bluetooth_tracker/
#
#- platform: bluetooth_tracker

# Example configuration.yaml entry

- platform: nmap_tracker
  hosts: 
    - 192.168.0.177 # Aaron iPhone
    - 192.168.0.77 # iPad Mini
    - 192.168.0.11 # Big iPad
    - 192.168.0.143 # Kid Phone
