#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

language: python

python:
  - "3.6"

before_install:
  - cp secrets-dummy.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)
  # Fix for missing homeassistant-ptozw 0.1.4 and pydispatcher 2.0.5
  # @link https://community.home-assistant.io/t/travis-ci-build-issues/119482
  - sudo apt-get install -y libudev-dev

install:
  - pip3 install homeassistant==${HA_VERSION}

script:
  - hass --script check_config --config . --files
