#
# View
#
configuration_view:
  view: yes
  name: Configuration
  icon: mdi:settings
  entities:
    - group.modes
    - group.configuration
    - group.automations
    - group.automations_modes
    - group.automations_devices
    - group.automations_areas
    - group.automations_notifications
    # - group.counters


#
# Groups
#
modes:
  name: Modes
  control: hidden
  entities:
    - input_boolean.night_mode
    - input_boolean.nap_mode
    - input_boolean.quiet_mode
    - input_boolean.low_mode
    - input_boolean.scene_mode

automations:
  name: Automations
  control: hidden
  entities:
    - automation.homekit_start
    - automation.scene_daylight
    - automation.scene_gaming
    - automation.scene_romantic
    - automation.scene_select
    - automation.theme_auto
    - automation.wake_up

automations_devices:
  name: Devices Automations
  control: hidden
  entities:
    - automation.nightlight_off
    - automation.nightlight_on
    - automation.scene_effect
    - automation.tv_off
    - automation.video_player_resume
    - automation.video_player_stop

automations_modes:
  name: Modes Automations
  control: hidden
  entities:
    - automation.low_power_mode_start
    - automation.low_power_mode_stop
    - automation.motion_detection_auto
    - automation.nap_mode_start
    - automation.nap_mode_stop
    - automation.night_mode_start
    - automation.night_mode_stop
    - automation.quiet_mode_start
    - automation.quiet_mode_stop

automations_notifications:
  name: Notifications Automations
  control: hidden
  entities:
    - automation.daily_greeting
    - automation.door_notify
    - automation.door_notify_reset
    - automation.front_door_notify
    - automation.power_supply_notify
    - automation.update_notify

configuration:
  name: Configuration Switches
  control: hidden
  entities:
    - input_boolean.door_test
    - sensor.door_status
    - input_boolean.motion_test
    - sensor.motion_status
