#
# View
#
default_view:
  view: yes
  icon: mdi:home-assistant
  entities:
    - group.notifications
    - group.wallpaper
    - group.now
    - group.public_transit
    - group.climate
    - group.actions
    - group.security
    - group.presence


#
# Groups
#
actions:
  name: Actions
  control: hidden
  entities:
    - script.wake_up
    - input_select.scene
    - input_boolean.night_mode
    - input_boolean.nap_mode
    - input_boolean.quiet_mode
    - input_boolean.low_mode

now:
  name: " "
  entities:
    - sensor.date_friendly
    - sensor.time_friendly
    - sensor.sun_state

presence:
  name: Presence
  control: hidden
  entities:
    - device_tracker.cellphone_her
    - device_tracker.cellphone_him

security:
  name: Security Status
  control: hidden
  entities:
    - sensor.door_status
    - sensor.motion_status

wallpaper:
  name: " "
  entities:
    - camera.bing_wallpaper
    - sensor.bing_wallpaper
