- platform: plex_recently_added
  name: Plex Recently Added Movies # will create sensor.recently_added_movies
  token: !secret plex_token
  host: !secret plex_host
  port: 32400
  section_types:
  - movie

- platform: plex_recently_added
  name: Plex Recently Added TV  # will create sensor.recently_added_tv
  token: !secret plex_token
  host: !secret plex_host
  port: 32400
  section_types:
  - show