#
# Door status
#
# Returns a comma-separated list of doors currently open.
#
# @see /automations/notifications/door_notify.yaml
#
- platform: template
  sensors:
    door_location:
      value_template: >-
        {% set entities = [
            states.binary_sensor.front_door,
            states.input_boolean.door_test,
          ]
        %}
        {% set value = entities | selectattr('state', 'equalto', 'on')
                                | map(attribute='name')
                                | join(',') %}
        {% set value = value | replace(" Multisensor", "") %}
        {% set value = value | replace(" Sensor", null) %}
        {% set value = value | replace(",", ", ") %}

        {{ value }}

    door_status:
      friendly_name: Doors
      friendly_name_template: >-
        {% if is_state('group.door_sensors', 'on') %}
          Door open
        {% else %}
          External doors
        {% endif %}
      icon_template: >-
        {% if is_state('group.door_sensors', 'on') %}
          mdi:door-open
        {% else %}
          mdi:door-closed
        {% endif %}
      value_template: >-
        {% set value = states('sensor.door_location') %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Closed
        {% endif %}


#
# Leak detection status
#
# Returns a comma-separated list of locations where leaks are detected.
#
# @see /automations/notifications/leak_notify.yaml
#
- platform: template
  sensors:
    leak_location:
      value_template: >-
        {% set entities = [
            states.binary_sensor.kitchen_leak_sensor,
            states.binary_sensor.washroom_leak_sensor,
            states.input_boolean.leak_test,
          ]
        %}
        {% set value = entities | selectattr('state', 'equalto', 'on')
                                | map(attribute='name')
                                | join(',') %}
        {% set value = value | replace(" Sensor", null) %}
        {% set value = value | replace(",", ", ") %}

        {{ value }}

    # leak_status:
    #   friendly_name: Leaks
    #   friendly_name_template: >-
    #     {% if is_state('group.leak_sensors', 'on') %}
    #       Leak detected
    #     {% else %}
    #       Leaks
    #     {% endif %}
    #   icon_template: >-
    #     {% if is_state('group.leak_sensors', 'on') %}
    #       mdi:pipe-leak
    #     {% else %}
    #       mdi:pipe
    #     {% endif %}
    #   value_template: >-
    #     {% set value = states('sensor.leak_location') %}

    #     {% if value != '' %}
    #       {{ value }}
    #     {% else %}
    #       Clear
    #     {% endif %}


#
# Motion detection status
#
# Returns a comma-separated list of locations where motion is detected.
#
# @see https://community.home-assistant.io/t/jinja2-expert-help-needed/10183/26
#
- platform: template
  sensors:
    motion_location:
      value_template: >-
        {% set entities = [
            states.binary_sensor.ring_basement_door_motion,
            states.binary_sensor.ring_front_door_motion,
            states.binary_sensor.ring_uphill_side_motion,
          ]
        %}
        {% set value = entities | selectattr('state', 'equalto', 'on')
                                | map(attribute='name')
                                | join(',') %}
        {% set value = value | replace(" Multisensor", null) %}
        {% set value = value | replace(" Sensor", null) %}
        {% set value = value | replace(" Motion", null) %}
        {% set value = value | replace(",", ", ") %}

        {{ value }}

    motion_status:
      friendly_name: Motion
      friendly_name_template: >-
        {% if is_state('group.motion_sensors', 'on') %}
          Motion detected
        {% else %}
          Motion
        {% endif %}
      icon_template: >-
        {% if is_state('group.motion_sensors', 'on') %}
          mdi:run
        {% else %}
          mdi:radar
        {% endif %}
      value_template: >-
        {% set value = states('sensor.motion_location') %}

        {% if value != '' %}
          {{ value }}
        {% else %}
          Clear
        {% endif %}
